name: pdx-exomeseq
channels:
- r
- bioconda
- conda-forge
dependencies:
- pandas=0.21.0
- pyyaml=3.12
- r::r-tidyverse=1.1.1
- r::r-devtools=1.13.3
- conda-forge::plotnine=0.3.0
- bioconda::ngs-disambiguate=2016.11.10
- bioconda::bamtools=2.4.0
- bioconda::trim-galore=0.4.4
- bioconda::cutadapt=1.14
- bioconda::bwa=0.7.16
- bioconda::samtools=0.1.16
- bioconda::picard=2.14.0
- bioconda::gatk=3.8
- bioconda::fastqc=0.11.5
- bioconda::multiqc=0.9
